# 2. part- I

In [ ]:
#### importing libraries

In [124]:
import pandas as pand
import numpy as nump
import matplotlib
import matplotlib.pyplot as plot
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set(color_codes=True)
import pandas as pd
%matplotlib inline
from statsmodels.tsa.seasonal import seasonal_decompose

In [125]:
#### importing dataset

In [126]:
data = pd.read_csv('D:/P2_Data.csv')

In [127]:
data.head()

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
0,-2.30325,15.4530,853.76,-490.50,0.06,-11.2440,-1400.762,-22435.144,1535.900,-3.41000,...,9.8594,1,-5956.56,1.4626,-22.547,-9.2880,1.50200,-7870.52,16.02,True
1,-3.79380,8.2308,1077.72,-2340.20,2.06,-6.6428,-949.740,-22459.770,-562.100,-0.52780,...,15.5520,1,-5927.34,1.0864,-20.974,-13.7370,0.47138,-15984.08,NaN,False
2,-4.21470,7.7925,-4559.32,90.20,2.06,-6.9420,-1814.340,-22446.333,1238.500,-0.19285,...,12.4780,1,-5000.22,3.8200,-11.028,-7.3965,0.96080,-8012.68,NaN,True
3,-2.95410,7.5495,518.68,-565.70,0.06,-6.7114,-1346.520,-22414.960,1084.376,-0.53640,...,9.0148,1,-3457.32,5.0020,-25.280,-6.6633,1.04010,-8243.48,13.92,False
4,-2.67390,7.1814,891.36,-379.55,0.06,-10.6000,-1062.340,-22417.580,1016.740,-2.61700,...,10.1046,1,-5110.32,7.9840,-13.402,-8.6394,0.66500,-9224.08,16.16,True

In [128]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
0,-2.30325,15.4530,853.76,-490.50,0.06,-11.2440,-1400.762,-22435.144,1535.900,-3.41000,...,9.859400,1,-5956.56,1.4626,-22.5470,-9.2880,1.50200,-7870.52,16.02,True
1,-3.79380,8.2308,1077.72,-2340.20,2.06,-6.6428,-949.740,-22459.770,-562.100,-0.52780,...,15.552000,1,-5927.34,1.0864,-20.9740,-13.7370,0.47138,-15984.08,NaN,False
2,-4.21470,7.7925,-4559.32,90.20,2.06,-6.9420,-1814.340,-22446.333,1238.500,-0.19285,...,12.478000,1,-5000.22,3.8200,-11.0280,-7.3965,0.96080,-8012.68,NaN,True
3,-2.95410,7.5495,518.68,-565.70,0.06,-6.7114,-1346.520,-22414.960,1084.376,-0.53640,...,9.014800,1,-3457.32,5.0020,-25.2800,-6.6633,1.04010,-8243.48,13.92,False
4,-2.67390,7.1814,891.36,-379.55,0.06,-10.6000,-1062.340,-22417.580,1016.740,-2.61700,...,10.104600,1,-5110.32,7.9840,-13.4020,-8.6394,0.66500,-9224.08,16.16,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,-2.92770,8.8188,802.44,-529.00,2.06,-9.2520,-1250.420,-22528.130,1021.000,-2.62300,...,8.620234,1,-5791.41,5.5820,-18.0740,-14.3160,0.62440,-7785.28,NaN,True
996,-4.10040,12.7560,-3.12,-782.80,2.06,-8.0254,-1365.180,-22430.153,4107.500,-0.18675,...,10.036800,1,-6954.12,0.8285,-14.9616,-7.3242,0.84230,-7687.08,12.75,False
997,-3.20340,13.7160,581.88,-604.70,2.06,-8.1662,-1350.480,-22531.400,154.100,-0.29060,...,12.250000,0,-5400.12,1.0950,-20.4510,-8.6283,0.53430,-7770.98,NaN,False
998,-5.12400,7.9398,990.68,-607.70,2.06,-7.7398,-1406.362,-22456.000,2946.100,-3.77100,...,9.427800,1,-6389.52,1.0516,-13.2810,-10.7070,0.84800,-7794.68,14.36,False
999,-6.40200,7.2063,811.82,-392.04,0.06,-8.4240,-1897.340,-22360.860,1304.300,-0.89120,...,8.706860,0,-6243.69,3.4700,-6.7160,-10.1220,0.54190,-10349.08,13.62,True

In [129]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 22 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   F1      1000 non-null   float64
 1   F2      1000 non-null   float64
 2   F3      1000 non-null   float64
 3   F4      1000 non-null   float64
 4   F5      1000 non-null   float64
 5   F6      1000 non-null   float64
 6   F7      1000 non-null   float64
 7   F8      1000 non-null   float64
 8   F9      1000 non-null   float64
 9   F10     1000 non-null   float64
 10  F11     1000 non-null   int64
 11  F12     1000 non-null   float64
 12  F13     1000 non-null   float64
 13  F14     1000 non-null   int64
 14  F15     1000 non-null   float64
 15  F16     1000 non-null   float64
 16  F17     1000 non-null   float64
 17  F18     1000 non-null   float64
 18  F19     1000 non-null   float64
 19  F20     1000 non-null   float64
 20  F21     500 non-null    float64
 21  Class   1000 non-null   bool
dtypes: bool(1), float64(19), int64(2)
memory usage: 165.2 KB

In [130]:
### null value checking

In [131]:
data.isna().sum()

F1         0
F2         0
F3         0
F4         0
F5         0
F6         0
F7         0
F8         0
F9         0
F10        0
F11        0
F12        0
F13        0
F14        0
F15        0
F16        0
F17        0
F18        0
F19        0
F20        0
F21      500
Class      0
dtype: int64

In [132]:
## data preprocessing 
data = data.dropna()

In [133]:
print(data)

          F1       F2       F3      F4    F5       F6        F7         F8  \
0   -2.30325  15.4530   853.76 -490.50  0.06 -11.2440 -1400.762 -22435.144
3   -2.95410   7.5495   518.68 -565.70  0.06  -6.7114 -1346.520 -22414.960
4   -2.67390   7.1814   891.36 -379.55  0.06 -10.6000 -1062.340 -22417.580
7   -5.10000   7.7787   983.76 -567.30  0.06  -9.4360  -601.340 -22599.450
8   -2.36025  14.1690   477.28 -294.00  2.06  -7.7058 -1463.060 -22532.410
..       ...      ...      ...     ...   ...      ...       ...        ...
993 -6.49500   7.4910  -314.72 -340.81  2.06  -8.7060 -1838.940 -22403.970
994 -4.96050  10.6890  1185.48 -522.90  2.06  -9.0880 -1261.220 -22405.680
996 -4.10040  12.7560    -3.12 -782.80  2.06  -8.0254 -1365.180 -22430.153
998 -5.12400   7.9398   990.68 -607.70  2.06  -7.7398 -1406.362 -22456.000
999 -6.40200   7.2063   811.82 -392.04  0.06  -8.4240 -1897.340 -22360.860

           F9      F10  ...       F13  F14      F15     F16      F17      F18  \
0    1535.900 -3.41000  ...   9.85940    1 -5956.56  1.4626 -22.5470  -9.2880
3    1084.376 -0.53640  ...   9.01480    1 -3457.32  5.0020 -25.2800  -6.6633
4    1016.740 -2.61700  ...  10.10460    1 -5110.32  7.9840 -13.4020  -8.6394
7    -954.500 -3.56400  ...   8.76392    1 -4969.02  1.1510  -8.9050  -8.6028
8    1191.680 -0.91160  ...   8.65182    0 -5187.42  5.0020 -15.7320  -7.8333
..        ...      ...  ...       ...  ...      ...     ...      ...      ...
993  1170.840 -0.39650  ...   9.46700    1 -4846.32  5.5880 -15.1408  -7.2846
994   546.900 -0.67320  ...   9.35020    1 -5867.37  1.8738 -15.0573 -11.1030
996  4107.500 -0.18675  ...  10.03680    1 -6954.12  0.8285 -14.9616  -7.3242
998  2946.100 -3.77100  ...   9.42780    1 -6389.52  1.0516 -13.2810 -10.7070
999  1304.300 -0.89120  ...   8.70686    0 -6243.69  3.4700  -6.7160 -10.1220

        F19       F20    F21  Class
0    1.5020  -7870.52  16.02   True
3    1.0401  -8243.48  13.92  False
4    0.6650  -9224.08  16.16   True
7    0.6651  -7263.68  13.23  False
8    1.9670  -7834.46  14.02   True
..      ...       ...    ...    ...
993  1.2596  -7863.05  15.92   True
994  2.7300  -8078.68  15.38  False
996  0.8423  -7687.08  12.75  False
998  0.8480  -7794.68  14.36  False
999  0.5419 -10349.08  13.62   True

[500 rows x 22 columns]

In [134]:
data.isna().sum()

F1       0
F2       0
F3       0
F4       0
F5       0
F6       0
F7       0
F8       0
F9       0
F10      0
F11      0
F12      0
F13      0
F14      0
F15      0
F16      0
F17      0
F18      0
F19      0
F20      0
F21      0
Class    0
dtype: int64

In [135]:
data.dtypes

F1       float64
F2       float64
F3       float64
F4       float64
F5       float64
F6       float64
F7       float64
F8       float64
F9       float64
F10      float64
F11        int64
F12      float64
F13      float64
F14        int64
F15      float64
F16      float64
F17      float64
F18      float64
F19      float64
F20      float64
F21      float64
Class       bool
dtype: object

In [136]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
0,-2.30325,15.4530,853.76,-490.50,0.06,-11.2440,-1400.762,-22435.144,1535.900,-3.41000,...,9.85940,1,-5956.56,1.4626,-22.5470,-9.2880,1.5020,-7870.52,16.02,True
3,-2.95410,7.5495,518.68,-565.70,0.06,-6.7114,-1346.520,-22414.960,1084.376,-0.53640,...,9.01480,1,-3457.32,5.0020,-25.2800,-6.6633,1.0401,-8243.48,13.92,False
4,-2.67390,7.1814,891.36,-379.55,0.06,-10.6000,-1062.340,-22417.580,1016.740,-2.61700,...,10.10460,1,-5110.32,7.9840,-13.4020,-8.6394,0.6650,-9224.08,16.16,True
7,-5.10000,7.7787,983.76,-567.30,0.06,-9.4360,-601.340,-22599.450,-954.500,-3.56400,...,8.76392,1,-4969.02,1.1510,-8.9050,-8.6028,0.6651,-7263.68,13.23,False
8,-2.36025,14.1690,477.28,-294.00,2.06,-7.7058,-1463.060,-22532.410,1191.680,-0.91160,...,8.65182,0,-5187.42,5.0020,-15.7320,-7.8333,1.9670,-7834.46,14.02,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,-6.49500,7.4910,-314.72,-340.81,2.06,-8.7060,-1838.940,-22403.970,1170.840,-0.39650,...,9.46700,1,-4846.32,5.5880,-15.1408,-7.2846,1.2596,-7863.05,15.92,True
994,-4.96050,10.6890,1185.48,-522.90,2.06,-9.0880,-1261.220,-22405.680,546.900,-0.67320,...,9.35020,1,-5867.37,1.8738,-15.0573,-11.1030,2.7300,-8078.68,15.38,False
996,-4.10040,12.7560,-3.12,-782.80,2.06,-8.0254,-1365.180,-22430.153,4107.500,-0.18675,...,10.03680,1,-6954.12,0.8285,-14.9616,-7.3242,0.8423,-7687.08,12.75,False
998,-5.12400,7.9398,990.68,-607.70,2.06,-7.7398,-1406.362,-22456.000,2946.100,-3.77100,...,9.42780,1,-6389.52,1.0516,-13.2810,-10.7070,0.8480,-7794.68,14.36,False
999,-6.40200,7.2063,811.82,-392.04,0.06,-8.4240,-1897.340,-22360.860,1304.300,-0.89120,...,8.70686,0,-6243.69,3.4700,-6.7160,-10.1220,0.5419,-10349.08,13.62,True

In [137]:
### string to int value

In [138]:
data[["Class"]] = data[["Class"]].apply(lambda col:pd.Categorical(col).codes)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [139]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
0,-2.30325,15.4530,853.76,-490.50,0.06,-11.2440,-1400.762,-22435.144,1535.900,-3.41000,...,9.85940,1,-5956.56,1.4626,-22.5470,-9.2880,1.5020,-7870.52,16.02,1
3,-2.95410,7.5495,518.68,-565.70,0.06,-6.7114,-1346.520,-22414.960,1084.376,-0.53640,...,9.01480,1,-3457.32,5.0020,-25.2800,-6.6633,1.0401,-8243.48,13.92,0
4,-2.67390,7.1814,891.36,-379.55,0.06,-10.6000,-1062.340,-22417.580,1016.740,-2.61700,...,10.10460,1,-5110.32,7.9840,-13.4020,-8.6394,0.6650,-9224.08,16.16,1
7,-5.10000,7.7787,983.76,-567.30,0.06,-9.4360,-601.340,-22599.450,-954.500,-3.56400,...,8.76392,1,-4969.02,1.1510,-8.9050,-8.6028,0.6651,-7263.68,13.23,0
8,-2.36025,14.1690,477.28,-294.00,2.06,-7.7058,-1463.060,-22532.410,1191.680,-0.91160,...,8.65182,0,-5187.42,5.0020,-15.7320,-7.8333,1.9670,-7834.46,14.02,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,-6.49500,7.4910,-314.72,-340.81,2.06,-8.7060,-1838.940,-22403.970,1170.840,-0.39650,...,9.46700,1,-4846.32,5.5880,-15.1408,-7.2846,1.2596,-7863.05,15.92,1
994,-4.96050,10.6890,1185.48,-522.90,2.06,-9.0880,-1261.220,-22405.680,546.900,-0.67320,...,9.35020,1,-5867.37,1.8738,-15.0573,-11.1030,2.7300,-8078.68,15.38,0
996,-4.10040,12.7560,-3.12,-782.80,2.06,-8.0254,-1365.180,-22430.153,4107.500,-0.18675,...,10.03680,1,-6954.12,0.8285,-14.9616,-7.3242,0.8423,-7687.08,12.75,0
998,-5.12400,7.9398,990.68,-607.70,2.06,-7.7398,-1406.362,-22456.000,2946.100,-3.77100,...,9.42780,1,-6389.52,1.0516,-13.2810,-10.7070,0.8480,-7794.68,14.36,0
999,-6.40200,7.2063,811.82,-392.04,0.06,-8.4240,-1897.340,-22360.860,1304.300,-0.89120,...,8.70686,0,-6243.69,3.4700,-6.7160,-10.1220,0.5419,-10349.08,13.62,1

In [140]:
### splitting into test and train

In [141]:
x=data.drop("Class", axis=1)

In [142]:
y=data["Class"]

In [143]:
x

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21
0,-2.30325,15.4530,853.76,-490.50,0.06,-11.2440,-1400.762,-22435.144,1535.900,-3.41000,...,-184.8900,9.85940,1,-5956.56,1.4626,-22.5470,-9.2880,1.5020,-7870.52,16.02
3,-2.95410,7.5495,518.68,-565.70,0.06,-6.7114,-1346.520,-22414.960,1084.376,-0.53640,...,-125.9520,9.01480,1,-3457.32,5.0020,-25.2800,-6.6633,1.0401,-8243.48,13.92
4,-2.67390,7.1814,891.36,-379.55,0.06,-10.6000,-1062.340,-22417.580,1016.740,-2.61700,...,-167.2500,10.10460,1,-5110.32,7.9840,-13.4020,-8.6394,0.6650,-9224.08,16.16
7,-5.10000,7.7787,983.76,-567.30,0.06,-9.4360,-601.340,-22599.450,-954.500,-3.56400,...,-107.0763,8.76392,1,-4969.02,1.1510,-8.9050,-8.6028,0.6651,-7263.68,13.23
8,-2.36025,14.1690,477.28,-294.00,2.06,-7.7058,-1463.060,-22532.410,1191.680,-0.91160,...,-114.3030,8.65182,0,-5187.42,5.0020,-15.7320,-7.8333,1.9670,-7834.46,14.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,-6.49500,7.4910,-314.72,-340.81,2.06,-8.7060,-1838.940,-22403.970,1170.840,-0.39650,...,-152.4600,9.46700,1,-4846.32,5.5880,-15.1408,-7.2846,1.2596,-7863.05,15.92
994,-4.96050,10.6890,1185.48,-522.90,2.06,-9.0880,-1261.220,-22405.680,546.900,-0.67320,...,-187.7100,9.35020,1,-5867.37,1.8738,-15.0573,-11.1030,2.7300,-8078.68,15.38
996,-4.10040,12.7560,-3.12,-782.80,2.06,-8.0254,-1365.180,-22430.153,4107.500,-0.18675,...,-138.1500,10.03680,1,-6954.12,0.8285,-14.9616,-7.3242,0.8423,-7687.08,12.75
998,-5.12400,7.9398,990.68,-607.70,2.06,-7.7398,-1406.362,-22456.000,2946.100,-3.77100,...,-214.1100,9.42780,1,-6389.52,1.0516,-13.2810,-10.7070,0.8480,-7794.68,14.36
999,-6.40200,7.2063,811.82,-392.04,0.06,-8.4240,-1897.340,-22360.860,1304.300,-0.89120,...,-210.3000,8.70686,0,-6243.69,3.4700,-6.7160,-10.1220,0.5419,-10349.08,13.62

In [144]:
y

0      1
3      0
4      1
7      0
8      1
      ..
993    1
994    0
996    0
998    0
999    1
Name: Class, Length: 500, dtype: int8

In [145]:
from sklearn.model_selection import train_test_split

In [146]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [147]:
x_train

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21
491,-3.13110,10.1130,713.880,-195.7000,2.06,-8.4142,-1618.940,-22385.390,1242.70,-1.5130,...,-110.967,9.052400,1,-5821.020,5.87000,-14.9796,-9.84300,1.0591,-7773.88,14.72
882,-3.12720,10.3440,970.094,-287.6000,0.06,-7.7740,-1504.780,-22381.870,2506.30,-1.8920,...,-126.186,8.663700,0,-6085.491,1.13840,-17.3960,-11.51400,3.5900,-7872.26,15.38
957,-2.63730,7.1931,759.680,-386.7300,0.06,-10.7160,-1372.580,-22524.630,1042.50,-0.7644,...,-149.340,8.620649,1,-5593.620,2.29260,-22.7980,-9.00930,2.4330,-8019.88,15.09
106,-2.99280,11.5080,344.680,-590.4000,2.06,-8.9360,-1381.740,-22432.509,3643.50,-0.9472,...,-158.130,8.679340,1,-5849.460,0.79652,-10.3050,-9.26670,0.5693,-8353.18,15.97
773,-4.83060,12.2280,1115.460,-402.3821,0.06,-9.0480,-1410.350,-22431.404,1180.86,-0.6184,...,-111.432,8.620337,1,-5761.380,1.67880,-17.0330,-8.84970,0.6856,-7650.08,15.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
516,-5.91600,8.3613,1223.480,-74.6000,0.06,-6.7272,-1355.780,-22468.700,581.10,-0.7835,...,-113.517,8.802040,0,-5476.920,1.04060,-21.3270,-9.09900,0.6701,-7149.08,15.62
149,-6.72300,10.6740,-733.720,-358.9900,0.06,-6.6338,-1482.500,-22448.800,1728.50,-0.3841,...,-132.522,10.036600,1,-3976.020,1.50280,-9.1250,-6.52761,0.5387,-9754.08,14.85
808,-2.23347,7.1316,1079.820,-320.3000,2.06,-11.7220,-2510.340,-22382.320,1185.06,-0.7254,...,-156.540,10.135200,0,-5842.470,4.53400,-17.1150,-11.20200,0.7990,-7462.78,15.79
486,-4.18230,10.4190,1097.200,192.1000,0.06,-6.8550,-1455.760,-22430.025,1102.80,-0.9671,...,-218.340,8.867800,0,-5787.780,6.38600,-26.5600,-8.14170,1.7930,-8069.58,16.72
65,-7.20000,9.9120,561.680,-1362.6000,0.06,-6.7238,-1406.054,-22467.530,2672.70,-1.0648,...,-148.530,9.106000,0,-6119.220,0.94880,-4.3400,-11.70300,2.8750,-8062.18,16.62

In [148]:
x_test

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21
623,-2.37450,8.80410,919.680,-439.76,0.06,-7.5556,-1273.22,-22400.710,815.10,-1.1430,...,-138.810,9.75400,1,-5423.52,2.47760,-12.430,-9.0882,0.6423,-9140.08,15.41
704,-6.54000,10.00500,644.080,461.70,2.06,-6.7140,-1507.40,-22416.640,1659.70,-0.8447,...,-122.418,8.88440,0,-5578.32,1.25320,-10.937,-7.7085,1.9830,-8136.48,15.50
85,-8.48400,10.75800,1482.680,-1171.90,2.06,-7.0528,-1353.64,-22374.360,1455.90,-0.4022,...,-112.845,8.64962,1,-6550.02,2.08900,-20.099,-10.3860,0.5722,-9287.08,12.93
140,-4.81680,7.45950,979.220,-360.42,2.06,-11.3440,-1037.34,-22441.776,-3904.50,-0.2897,...,-147.360,9.67520,1,3988.98,0.86242,-10.886,-6.6981,1.4240,-7650.98,12.74
964,-10.17000,8.72760,990.060,-474.40,2.06,-7.2828,-1445.88,-22402.140,3521.50,-1.2000,...,-112.194,9.02760,1,-6218.19,0.85742,-19.784,-7.3671,0.5535,-7772.58,14.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,-3.14550,9.33390,822.240,-711.10,2.06,-8.8420,-1063.14,-22411.590,861.10,-1.5630,...,-130.494,8.71462,0,-5715.42,4.28800,-13.617,-9.5160,3.1040,-8088.08,15.35
404,-4.47330,15.66300,682.880,-691.90,2.06,-6.6542,-1395.28,-22449.260,-41.10,-0.3432,...,-207.660,10.71200,1,-4054.92,0.86006,-12.812,-6.8511,1.0208,-8320.18,14.04
181,-3.30090,7.01649,961.508,-1632.20,0.06,-6.8120,1020.46,-22437.853,107.10,-4.4990,...,-122.451,12.00800,1,-5365.02,1.25860,-11.941,-8.8365,1.8200,-7780.58,14.18
465,-2.20761,12.06900,-97.920,-328.22,2.06,-7.6344,-1456.82,-22451.270,1130.36,-0.4079,...,-116.151,9.83600,0,-4843.62,7.46600,-17.733,-6.9234,0.5536,-9477.08,15.86
220,-8.07600,7.92270,1063.460,-645.20,0.06,-8.5040,-856.74,-22465.560,432.10,-0.4500,...,-118.596,8.87620,0,-5298.42,1.40820,-13.034,-6.9990,0.5682,-10122.08,13.15

In [149]:
y_train

491    1
882    0
957    1
106    1
773    0
      ..
516    0
149    1
808    0
486    1
65     1
Name: Class, Length: 400, dtype: int8

In [150]:
y_test

623    0
704    1
85     0
140    0
964    0
      ..
24     1
404    0
181    0
465    1
220    1
Name: Class, Length: 100, dtype: int8

In [151]:
#### decision tree classifier

In [152]:
from sklearn.tree import DecisionTreeClassifier

In [153]:
dtc=DecisionTreeClassifier()

In [154]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier()

In [155]:
y_pred=dtc.predict(x_test)

In [156]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [157]:
#### accuracy

In [158]:
accuracy_score(y_pred,y_test)

0.74

In [159]:
### confusion matrix

In [160]:
confusion_matrix(y_pred,y_test)

array([[32, 16],
       [10, 42]], dtype=int64)

In [161]:
#### random forest classifier

In [162]:
from sklearn.ensemble import RandomForestClassifier

In [163]:
clf=RandomForestClassifier(n_estimators=100)

In [164]:
#### train the model

In [165]:
clf.fit(x_train,y_train)

RandomForestClassifier()

In [171]:
y_pred1=clf.predict(x_test)

In [167]:
from sklearn.metrics import accuracy_score

In [168]:
### accuracy

In [172]:
print("Accuracy:",accuracy_score(y_test, y_pred1))

Accuracy: 0.78

In [ ]:
#### support vector machine

In [ ]:
### importing the SVM model

In [173]:
from sklearn import svm

In [ ]:
#### SVM classifier

In [175]:
clf = svm.SVC(kernel='linear')

In [ ]:
### training the model using training sets of data

In [177]:
clf.fit(x_train, y_train)

SVC(kernel='linear')

In [ ]:
## predict the response

In [179]:
y_pred2 = clf.predict(x_test)

In [ ]:
### for accuracy calculation

In [180]:
from sklearn import metrics

In [182]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred2))

Accuracy: 0.74

# Part-II

In [ ]:
#### dataset import

In [68]:
data = pd.read_csv('D:/P2_Test.csv')

In [70]:
data=data.drop("Class",axis=1)

In [71]:
data.isna().sum()

F1       0
F2       0
F3       0
F4       0
F5       0
F6       0
F7       0
F8       0
F9       0
F10      0
F11      0
F12      0
F13      0
F14      0
F15      0
F16      0
F17      0
F18      0
F19      0
F20      0
F21    500
dtype: int64

In [72]:
data=data.dropna()

In [73]:
data.isna().sum()

F1     0
F2     0
F3     0
F4     0
F5     0
F6     0
F7     0
F8     0
F9     0
F10    0
F11    0
F12    0
F13    0
F14    0
F15    0
F16    0
F17    0
F18    0
F19    0
F20    0
F21    0
dtype: int64

In [74]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21
1,-2.79000,7.4094,966.022,-695.70,2.06,-8.3732,-390.1400,-22432.843,876.90,-1.01370,...,-106.4214,10.060800,0,-5879.670,2.7520,-17.2890,-8.47740,0.99260,-8427.28,17.65
2,-2.11278,8.2713,888.640,-470.23,0.06,-8.1240,-1053.7400,-22468.030,465.90,-4.17600,...,-124.5720,11.942000,0,-5392.020,2.4664,-14.0058,-11.58300,0.51647,-12350.08,16.73
3,-2.16738,8.3199,961.672,-256.30,0.06,-9.0840,-1350.6000,-22478.680,707.50,-3.11300,...,-118.8240,8.638706,0,-4417.020,2.8500,-13.8889,-8.75580,3.28400,-7861.62,14.85
7,-6.96900,11.5320,549.280,-724.90,2.06,-7.0934,-1420.6640,-22449.270,1141.82,-0.93200,...,-115.0200,8.630760,1,-6512.520,7.5020,-15.9100,-6.74370,2.33100,-8083.68,15.25
8,-2.58930,7.1085,-560.520,-583.10,2.06,-7.8484,-283.9400,-22424.380,734.30,-0.41150,...,-158.4000,9.188400,1,10570.980,2.3890,-4.7540,-6.42711,0.51059,-11525.08,14.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,-5.91000,15.0900,-5727.320,-1032.00,2.06,-7.3606,-1385.2200,-22434.016,1669.10,-0.19287,...,-125.1150,10.415200,1,-5925.690,1.1650,-17.6060,-11.50500,1.95900,-7770.78,16.39
991,-5.57400,7.5237,1076.760,-481.08,0.06,-7.5620,-1377.7400,-22422.400,1440.50,-2.33500,...,-105.7719,8.728000,1,-6413.820,1.8912,-11.4770,-9.79800,1.14500,-8144.58,13.94
995,-4.79640,7.8531,241.280,-1574.20,0.06,-6.7650,-1319.3800,-22437.663,2217.30,-0.53810,...,-107.2713,10.280200,0,-6251.310,1.1114,-26.7800,-10.24800,2.40700,-8059.28,16.63
996,-3.01890,12.2190,971.684,-414.62,2.06,-12.4180,-1417.2106,-22422.070,1400.90,-2.72700,...,-110.6190,8.633086,1,-6078.102,1.6906,-18.1260,-17.61300,1.05020,-8088.68,15.96
997,-3.06540,14.4990,816.080,-1195.30,0.06,-7.1588,-1335.5600,-22494.620,695.90,-1.79100,...,-132.5910,9.838400,0,-3914.520,1.9832,-9.2050,-7.24950,0.92630,-7592.48,15.52

In [76]:
y_pred_new=dtc.predict(data)

In [79]:
y_pred_new

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1], dtype=int8)

In [87]:
data["Class"]=y_pred_new

In [88]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
1,-2.79000,7.4094,966.022,-695.70,2.06,-8.3732,-390.1400,-22432.843,876.90,-1.01370,...,10.060800,0,-5879.670,2.7520,-17.2890,-8.47740,0.99260,-8427.28,17.65,1
2,-2.11278,8.2713,888.640,-470.23,0.06,-8.1240,-1053.7400,-22468.030,465.90,-4.17600,...,11.942000,0,-5392.020,2.4664,-14.0058,-11.58300,0.51647,-12350.08,16.73,0
3,-2.16738,8.3199,961.672,-256.30,0.06,-9.0840,-1350.6000,-22478.680,707.50,-3.11300,...,8.638706,0,-4417.020,2.8500,-13.8889,-8.75580,3.28400,-7861.62,14.85,0
7,-6.96900,11.5320,549.280,-724.90,2.06,-7.0934,-1420.6640,-22449.270,1141.82,-0.93200,...,8.630760,1,-6512.520,7.5020,-15.9100,-6.74370,2.33100,-8083.68,15.25,0
8,-2.58930,7.1085,-560.520,-583.10,2.06,-7.8484,-283.9400,-22424.380,734.30,-0.41150,...,9.188400,1,10570.980,2.3890,-4.7540,-6.42711,0.51059,-11525.08,14.54,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,-5.91000,15.0900,-5727.320,-1032.00,2.06,-7.3606,-1385.2200,-22434.016,1669.10,-0.19287,...,10.415200,1,-5925.690,1.1650,-17.6060,-11.50500,1.95900,-7770.78,16.39,0
991,-5.57400,7.5237,1076.760,-481.08,0.06,-7.5620,-1377.7400,-22422.400,1440.50,-2.33500,...,8.728000,1,-6413.820,1.8912,-11.4770,-9.79800,1.14500,-8144.58,13.94,1
995,-4.79640,7.8531,241.280,-1574.20,0.06,-6.7650,-1319.3800,-22437.663,2217.30,-0.53810,...,10.280200,0,-6251.310,1.1114,-26.7800,-10.24800,2.40700,-8059.28,16.63,1
996,-3.01890,12.2190,971.684,-414.62,2.06,-12.4180,-1417.2106,-22422.070,1400.90,-2.72700,...,8.633086,1,-6078.102,1.6906,-18.1260,-17.61300,1.05020,-8088.68,15.96,1
997,-3.06540,14.4990,816.080,-1195.30,0.06,-7.1588,-1335.5600,-22494.620,695.90,-1.79100,...,9.838400,0,-3914.520,1.9832,-9.2050,-7.24950,0.92630,-7592.48,15.52,1

In [92]:
Class=[]
for i in data["Class"]:
    if(i==0):
        #data["Class"]="False"
        Class.append("False")
        #print("False")
    else:
        #data["Class"]="True"
        #print("True")
        Class.append("True")

In [93]:
Class

['True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'True',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'True',
 'True',
 'False',
 'True',
 'True',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'False',
 'True',
 'False',
 'True',
 'False',
 'False',
 'False',
 'False',
 'False',
 'True',
 'True',
 'True',
 'True']

In [85]:
for i in data["Class"]:
    if(i==0):
        data["Class"]="False"
    else:
        data["Class"]="True"

In [94]:
data["Class"]=Class

In [95]:
data

,F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,...,F13,F14,F15,F16,F17,F18,F19,F20,F21,Class
1,-2.79000,7.4094,966.022,-695.70,2.06,-8.3732,-390.1400,-22432.843,876.90,-1.01370,...,10.060800,0,-5879.670,2.7520,-17.2890,-8.47740,0.99260,-8427.28,17.65,True
2,-2.11278,8.2713,888.640,-470.23,0.06,-8.1240,-1053.7400,-22468.030,465.90,-4.17600,...,11.942000,0,-5392.020,2.4664,-14.0058,-11.58300,0.51647,-12350.08,16.73,False
3,-2.16738,8.3199,961.672,-256.30,0.06,-9.0840,-1350.6000,-22478.680,707.50,-3.11300,...,8.638706,0,-4417.020,2.8500,-13.8889,-8.75580,3.28400,-7861.62,14.85,False
7,-6.96900,11.5320,549.280,-724.90,2.06,-7.0934,-1420.6640,-22449.270,1141.82,-0.93200,...,8.630760,1,-6512.520,7.5020,-15.9100,-6.74370,2.33100,-8083.68,15.25,False
8,-2.58930,7.1085,-560.520,-583.10,2.06,-7.8484,-283.9400,-22424.380,734.30,-0.41150,...,9.188400,1,10570.980,2.3890,-4.7540,-6.42711,0.51059,-11525.08,14.54,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,-5.91000,15.0900,-5727.320,-1032.00,2.06,-7.3606,-1385.2200,-22434.016,1669.10,-0.19287,...,10.415200,1,-5925.690,1.1650,-17.6060,-11.50500,1.95900,-7770.78,16.39,False
991,-5.57400,7.5237,1076.760,-481.08,0.06,-7.5620,-1377.7400,-22422.400,1440.50,-2.33500,...,8.728000,1,-6413.820,1.8912,-11.4770,-9.79800,1.14500,-8144.58,13.94,True
995,-4.79640,7.8531,241.280,-1574.20,0.06,-6.7650,-1319.3800,-22437.663,2217.30,-0.53810,...,10.280200,0,-6251.310,1.1114,-26.7800,-10.24800,2.40700,-8059.28,16.63,True
996,-3.01890,12.2190,971.684,-414.62,2.06,-12.4180,-1417.2106,-22422.070,1400.90,-2.72700,...,8.633086,1,-6078.102,1.6906,-18.1260,-17.61300,1.05020,-8088.68,15.96,True
997,-3.06540,14.4990,816.080,-1195.30,0.06,-7.1588,-1335.5600,-22494.620,695.90,-1.79100,...,9.838400,0,-3914.520,1.9832,-9.2050,-7.24950,0.92630,-7592.48,15.52,True

In [ ]:
### converting data to csv

In [97]:
data.to_csv("D:/P2_Test_Predictions.csv")